openapi: 3.0.1
info:
  title: PolicingProfile_1.0.0-tsi.240104.1750+simulator.completeness
  version: 1.0.0

paths:
########################################################################################################################
#   PolicingProfile_1.0.0-tsi.240104.1750+simulator.completeness in static reference mode
########################################################################################################################
#
# At Application
# ==============
#
# Preparation => MountName=305250001, UUID=poliPro1
  /core-model-1-4:network-control-domain=cache/control-construct=305250001/profile-collection:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
      - $ref: '#/components/parameters/fields'
    get:
      operationId: getCachedProfileCollection
      summary: 'Provides ProfileCollection from cache'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      responses:
        '200':
          description: 'ProfileCollection provided from cache'
          content:
            application/json:
              schema:
                type: object
                required:
                  - core-model-1-4:profile-collection
                properties:
                  core-model-1-4:profile-collection:
                    type: object
                    properties:
                      profile:
                        type: array
                        minItems: 0
                        x-key: uuid
                        items:
                          type: object
                          required:
                            - uuid
                            - profile-name
                          properties:
                            uuid:
                              type: string
                              enum:
                                - 'poliPro1'
                            profile-name:
                              type: string
                              enum:
                                - 'policing-profile-1-0:PROFILE_NAME_TYPE_POLICING_PROFILE'
                example:
                  core-model-1-4:profile-collection:
                    profile:
                      - profile-name: 'policing-profile-1-0:PROFILE_NAME_TYPE_POLICING_PROFILE'
                        uuid: 'poliPro1'
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'

# Completeness of GET 200
  /core-model-1-4:network-control-domain=cache/control-construct=305250001/profile-collection/profile=poliPro1/policing-profile-1-0:policing-profile-pac/policing-profile-capability:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
      - $ref: '#/components/parameters/uuid'
      - $ref: '#/components/parameters/fields'
    get:
      operationId: getCachedPolicingProfileCapability
      summary: 'Provides PolicingProfileCapability from cache'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      responses:
        '200':
          description: 'PolicingProfileCapability provided from cache'
          content:
            application/json:
              schema:
                type: object
                required:
                  - policing-profile-1-0:policing-profile-capability
                properties:
                  policing-profile-1-0:policing-profile-capability:
                    $ref: '#/components/schemas/policing-profile-capability'
                example:
                  policing-profile-1-0:policing-profile-capability:
                    profile-naming-is-avail: true
                    supported-marker-mode-list:
                      - 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_BLIND'
                      - 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_AWARE'
                    supported-policer-kind-list:
                      - 'policing-profile-1-0:POLICER_KIND_TYPE_SINGLE_RATE_THREE_COLOR'
                      - 'policing-profile-1-0:POLICER_KIND_TYPE_TWO_RATE_THREE_COLOR'
                    information-rate-min: 0
                    information-rate-max: 10000000
                    burst-size-min: 0
                    burst-size-max: 32767
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
  /core-model-1-4:network-control-domain=cache/control-construct=305250001/profile-collection/profile=poliPro1/policing-profile-1-0:policing-profile-pac/policing-profile-configuration:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
      - $ref: '#/components/parameters/uuid'
      - $ref: '#/components/parameters/fields'
    get:
      operationId: getCachedPolicingProfileConfiguration
      summary: 'Provides PolicingProfileConfiguration from cache'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      responses:
        '200':
          description: 'PolicingProfileConfiguration provided from cache'
          content:
            application/json:
              schema:
                type: object
                required:
                  - policing-profile-1-0:policing-profile-configuration
                properties:
                  policing-profile-1-0:policing-profile-configuration:
                    $ref: '#/components/schemas/policing-profile-configuration'
                example:
                  policing-profile-1-0:policing-profile-configuration:
                    external-label: 'External label not yet defined.'
                    marker-mode: 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_BLIND'
                    policer-kind: 'policing-profile-1-0:POLICER_KIND_TYPE_SINGLE_RATE_THREE_COLOR'
                    committed-information-rate: 1000000
                    committed-burst-size: 512
                    excess-burst-size: -1
                    peak-information-rate: 100
                    peak-burst-size: 600
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'

# Completeness of RPC
  # /core-model-1-4:network-control-domain=live/control-construct=305250001/policing-profile-1-0:create-policing-profile => poliPro3
  /core-model-1-4:network-control-domain=live/control-construct=305250001/policing-profile-1-0%3Acreate-policing-profile:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
    post:
      operationId: postCreatePolicingProfile
      summary: 'Creates new instance of PolicingProfile'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - input
              properties:
                input:
                  type: object
                  required:
                    - marker-mode
                    - policer-kind
                    - committed-information-rate
                    - committed-burst-size
                  properties:
                    external-label:
                      type: string
                    marker-mode:
                      type: string
                      enum:
                        - 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_BLIND'
                        - 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_AWARE'
                        - 'policing-profile-1-0:MARKER_MODE_TYPE_NOT_YET_DEFINED'
                    policer-kind:
                      type: string
                      enum:
                        - 'policing-profile-1-0:POLICER_KIND_TYPE_SINGLE_RATE_THREE_COLOR'
                        - 'policing-profile-1-0:POLICER_KIND_TYPE_TWO_RATE_THREE_COLOR'
                        - 'policing-profile-1-0:POLICER_KIND_TYPE_NOT_YET_DEFINED'
                    committed-information-rate:
                      type: string
                    committed-burst-size:
                      type: string
                    excess-burst-size:
                      type: string
                    peak-information-rate:
                      type: string
                    peak-burst-size:
                      type: string
              example:
                input:
                  externalLabel = 'createdLabel'
                  markerMode = 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_BLIND'
                  policerKind = 'policing-profile-1-0:POLICER_KIND_TYPE_SINGLE_RATE_THREE_COLOR'
                  committedInformationRate = '10000'
                  committedBurstSize = '256'
                  excessBurstSize = '512'
                  peakInformationRate = '100000'
                  peakBurstSize = '512'
      responses:
        '200':
          description: 'New instance of PolicingProfile created'
          content:
            application/json:
              schema:
                type: object
                required:
                  - policing-profile-1-0:output
                properties:
                  policing-profile-1-0:output:
                    type: object
                    required:
                      - created-policing-profile
                    properties:
                      created-policing-profile:
                        type: string
                example:
                  policing-profile-1-0:output:
                    created-policing-profile: 'poliPro3'
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
  /core-model-1-4:network-control-domain=cache/control-construct=305250001/profile-collection/profile=poliPro3a/policing-profile-1-0:policing-profile-pac/policing-profile-configuration:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
      - $ref: '#/components/parameters/uuid'
      - $ref: '#/components/parameters/fields'
    get:
      operationId: getCachedPolicingProfileConfiguration
      summary: 'Provides PolicingProfileConfiguration from cache'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      responses:
        '200':
          description: 'PolicingProfileConfiguration provided from cache'
          content:
            application/json:
              schema:
                type: object
                required:
                  - policing-profile-1-0:policing-profile-configuration
                properties:
                  policing-profile-1-0:policing-profile-configuration:
                    $ref: '#/components/schemas/policing-profile-configuration'
                example:
                  policing-profile-1-0:policing-profile-configuration:
                    external-label: 'createdLabel'
                    marker-mode: 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_BLIND'
                    policer-kind: 'policing-profile-1-0:POLICER_KIND_TYPE_SINGLE_RATE_THREE_COLOR'
                    committed-information-rate: 10000
                    committed-burst-size: 256
                    excess-burst-size: -1
                    peak-information-rate: 100000
                    peak-burst-size: 512
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
  # /core-model-1-4:network-control-domain=live/control-construct=305250001/policing-profile-1-0:modify-policing-profile
  /core-model-1-4:network-control-domain=live/control-construct=305250001/policing-profile-1-0%3Amodify-policing-profile:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
    post:
      operationId: postModifyPolicingProfile
      summary: 'Modifies an existing PolicingProfile'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - input
              properties:
                input:
                  type: object
                  required:
                    - policing-profile-to-be-modified
                  properties:
                    policing-profile-to-be-modified:
                      type: string
                    external-label:
                      type: string
                    marker-mode:
                      type: string
                      enum:
                        - 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_BLIND'
                        - 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_AWARE'
                        - 'policing-profile-1-0:MARKER_MODE_TYPE_NOT_YET_DEFINED'
                    policer-kind:
                      type: string
                      enum:
                        - 'policing-profile-1-0:POLICER_KIND_TYPE_SINGLE_RATE_THREE_COLOR'
                        - 'policing-profile-1-0:POLICER_KIND_TYPE_TWO_RATE_THREE_COLOR'
                        - 'policing-profile-1-0:POLICER_KIND_TYPE_NOT_YET_DEFINED'
                    committed-information-rate:
                      type: string
                    committed-burst-size:
                      type: string
                    excess-burst-size:
                      type: string
                    peak-information-rate:
                      type: string
                    peak-burst-size:
                      type: string
              example:
                input:
                  policing-profile-to-be-modified = 'poliPro3'
                  externalLabel = 'modifiedLabel'
                  markerMode = 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_BLIND'
                  policerKind = 'policing-profile-1-0:POLICER_KIND_TYPE_SINGLE_RATE_THREE_COLOR'
                  committedInformationRate = '9999'
                  committedBurstSize = '128'
                  excessBurstSize = '256'
                  peakInformationRate = '99999'
                  peakBurstSize = '256'
      responses:
        '204':
          description: 'Instance of PolicingProfile updated'
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
  /core-model-1-4:network-control-domain=cache/control-construct=305250001/profile-collection/profile=poliPro3b/policing-profile-1-0:policing-profile-pac/policing-profile-configuration:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
      - $ref: '#/components/parameters/uuid'
      - $ref: '#/components/parameters/fields'
    get:
      operationId: getCachedPolicingProfileConfiguration
      summary: 'Provides PolicingProfileConfiguration from cache'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      responses:
        '200':
          description: 'PolicingProfileConfiguration provided from cache'
          content:
            application/json:
              schema:
                type: object
                required:
                  - policing-profile-1-0:policing-profile-configuration
                properties:
                  policing-profile-1-0:policing-profile-configuration:
                    $ref: '#/components/schemas/policing-profile-configuration'
                example:
                  policing-profile-1-0:policing-profile-configuration:
                    external-label: 'modifiedLabel'
                    marker-mode: 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_BLIND'
                    policer-kind: 'policing-profile-1-0:POLICER_KIND_TYPE_SINGLE_RATE_THREE_COLOR'
                    committed-information-rate: 9999
                    committed-burst-size: 128
                    excess-burst-size: -1
                    peak-information-rate: 99999
                    peak-burst-size: 256
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
  # /core-model-1-4:network-control-domain=live/control-construct=305250001/policing-profile-1-0:delete-policing-profile
  /core-model-1-4:network-control-domain=live/control-construct=305250001/policing-profile-1-0%3Adelete-policing-profile:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
    post:
      operationId: postDeletePolicingProfile
      summary: 'Deletes an instance of PolicingProfile'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - input
              properties:
                input:
                  type: object
                  required:
                  - obsolete-policing-profile
                  properties:
                    obsolete-policing-profile:
                      type: string
              example:
                input:
                  obsolete-policing-profile = 'poliPro3'
      responses:
        '204':
          description: 'Instance of PolicingProfile deleted'
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'


#
# At Controller (copy from above, different paths, less parameters, basicAuth, no headers)
# =============
#
# Preparation => MountName=305250001, UUID=poliPro1
  /rests/data/network-topology:network-topology/topology=topology-netconf/node=305250001/yang-ext:mount/core-model-1-4:control-construct/profile-collection:
    parameters:
      - $ref: '#/components/parameters/mountName'
      - $ref: '#/components/parameters/fields'
    get:
      operationId: getProfileCollection
      summary: 'Provides ProfileCollection from device'
      tags:
        - IndividualServices
      security:
        - basicAuth: []
      responses:
        '200':
          description: 'ProfileCollection provided from device'
          content:
            application/json:
              schema:
                type: object
                required:
                  - core-model-1-4:profile-collection
                properties:
                  core-model-1-4:profile-collection:
                    type: object
                    properties:
                      profile:
                        type: array
                        minItems: 0
                        x-key: uuid
                        items:
                          type: object
                          required:
                            - uuid
                            - profile-name
                          properties:
                            uuid:
                              type: string
                              enum:
                                - 'poliPro1'
                            profile-name:
                              type: string
                              enum:
                                - 'policing-profile-1-0:PROFILE_NAME_TYPE_POLICING_PROFILE'
                example:
                  core-model-1-4:profile-collection:
                    profile:
                      - profile-name: 'policing-profile-1-0:PROFILE_NAME_TYPE_POLICING_PROFILE'
                        uuid: 'poliPro1'

# Completeness of GET 200
  /rests/data/network-topology:network-topology/topology=topology-netconf/node=305250001/yang-ext:mount/core-model-1-4:control-construct/profile-collection/profile=poliPro1/policing-profile-1-0:policing-profile-pac/policing-profile-capability:
    parameters:
      - $ref: '#/components/parameters/mountName'
      - $ref: '#/components/parameters/uuid'
      - $ref: '#/components/parameters/fields'
    get:
      operationId: getPolicingProfileCapability
      summary: 'Provides PolicingProfileCapability from device'
      tags:
        - IndividualServices
      security:
        - basicAuth: []
      responses:
        '200':
          description: 'PolicingProfileCapability provided from device'
          content:
            application/json:
              schema:
                type: object
                required:
                  - policing-profile-1-0:policing-profile-capability
                properties:
                  policing-profile-1-0:policing-profile-capability:
                    $ref: '#/components/schemas/policing-profile-capability'
                example:
                  policing-profile-1-0:policing-profile-capability:
                    profile-naming-is-avail: true
                    supported-marker-mode-list:
                      - 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_BLIND'
                      - 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_AWARE'
                    supported-policer-kind-list:
                      - 'policing-profile-1-0:POLICER_KIND_TYPE_SINGLE_RATE_THREE_COLOR'
                      - 'policing-profile-1-0:POLICER_KIND_TYPE_TWO_RATE_THREE_COLOR'
                    information-rate-min: 0
                    information-rate-max: 10000000
                    burst-size-min: 0
                    burst-size-max: 32767
  /rests/data/network-topology:network-topology/topology=topology-netconf/node=305250001/yang-ext:mount/core-model-1-4:control-construct/profile-collection/profile=poliPro1/policing-profile-1-0:policing-profile-pac/policing-profile-configuration:
    parameters:
      - $ref: '#/components/parameters/mountName'
      - $ref: '#/components/parameters/uuid'
      - $ref: '#/components/parameters/fields'
    get:
      operationId: getPolicingProfileConfiguration
      summary: 'Provides PolicingProfileConfiguration from device'
      tags:
        - IndividualServices
      security:
        - basicAuth: []
      responses:
        '200':
          description: 'PolicingProfileConfiguration provided from device'
          content:
            application/json:
              schema:
                type: object
                required:
                  - policing-profile-1-0:policing-profile-configuration
                properties:
                  policing-profile-1-0:policing-profile-configuration:
                    $ref: '#/components/schemas/policing-profile-configuration'
                example:
                  policing-profile-1-0:policing-profile-configuration:
                    external-label: 'External label not yet defined.'
                    marker-mode: 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_BLIND'
                    policer-kind: 'policing-profile-1-0:POLICER_KIND_TYPE_SINGLE_RATE_THREE_COLOR'
                    committed-information-rate: 1000000
                    committed-burst-size: 512
                    excess-burst-size: -1
                    peak-information-rate: 100
                    peak-burst-size: 600

# Completeness of RPC
  # /rests/operations/network-topology:network-topology/topology=topology-netconf/node=305250001/yang-ext:mount/policing-profile-1-0:create-policing-profile => poliPro3
  /rests/operations/network-topology:network-topology/topology=topology-netconf/node=305250001/yang-ext:mount/policing-profile-1-0%3Acreate-policing-profile:
    parameters:
      - $ref: '#/components/parameters/mountName'
    post:
      operationId: postCreatePolicingProfile
      summary: 'Creates new instance of PolicingProfile'
      tags:
        - IndividualServices
      security:
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - input
              properties:
                input:
                  type: object
                  required:
                    - marker-mode
                    - policer-kind
                    - committed-information-rate
                    - committed-burst-size
                  properties:
                    external-label:
                      type: string
                    marker-mode:
                      type: string
                      enum:
                        - 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_BLIND'
                        - 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_AWARE'
                        - 'policing-profile-1-0:MARKER_MODE_TYPE_NOT_YET_DEFINED'
                    policer-kind:
                      type: string
                      enum:
                        - 'policing-profile-1-0:POLICER_KIND_TYPE_SINGLE_RATE_THREE_COLOR'
                        - 'policing-profile-1-0:POLICER_KIND_TYPE_TWO_RATE_THREE_COLOR'
                        - 'policing-profile-1-0:POLICER_KIND_TYPE_NOT_YET_DEFINED'
                    committed-information-rate:
                      type: string
                    committed-burst-size:
                      type: string
                    excess-burst-size:
                      type: string
                    peak-information-rate:
                      type: string
                    peak-burst-size:
                      type: string
              example:
                input:
                  externalLabel = 'createdLabel'
                  markerMode = 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_BLIND'
                  policerKind = 'policing-profile-1-0:POLICER_KIND_TYPE_SINGLE_RATE_THREE_COLOR'
                  committedInformationRate = '10000'
                  committedBurstSize = '256'
                  excessBurstSize = '512'
                  peakInformationRate = '100000'
                  peakBurstSize = '512'
      responses:
        '200':
          description: 'New instance of PolicingProfile created'
          content:
            application/json:
              schema:
                type: object
                required:
                  - policing-profile-1-0:output
                properties:
                  policing-profile-1-0:output:
                    type: object
                    required:
                      - created-policing-profile
                    properties:
                      created-policing-profile:
                        type: string
                example:
                  policing-profile-1-0:output:
                    created-policing-profile: 'poliPro3'
  /rests/data/network-topology:network-topology/topology=topology-netconf/node=305250001/yang-ext:mount/core-model-1-4:control-construct/profile-collection/profile=poliPro3a/policing-profile-1-0:policing-profile-pac/policing-profile-configuration:
    parameters:
      - $ref: '#/components/parameters/mountName'
      - $ref: '#/components/parameters/uuid'
      - $ref: '#/components/parameters/fields'
    get:
      operationId: getPolicingProfileConfiguration
      summary: 'Provides PolicingProfileConfiguration from device'
      tags:
        - IndividualServices
      security:
        - basicAuth: []
      responses:
        '200':
          description: 'PolicingProfileConfiguration provided from device'
          content:
            application/json:
              schema:
                type: object
                required:
                  - policing-profile-1-0:policing-profile-configuration
                properties:
                  policing-profile-1-0:policing-profile-configuration:
                    $ref: '#/components/schemas/policing-profile-configuration'
                example:
                  policing-profile-1-0:policing-profile-configuration:
                    external-label: 'createdLabel'
                    marker-mode: 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_BLIND'
                    policer-kind: 'policing-profile-1-0:POLICER_KIND_TYPE_SINGLE_RATE_THREE_COLOR'
                    committed-information-rate: 10000
                    committed-burst-size: 256
                    excess-burst-size: -1
                    peak-information-rate: 100000
                    peak-burst-size: 512
  # /rests/operations/network-topology:network-topology/topology=topology-netconf/node=305250001/yang-ext:mount/policing-profile-1-0:modify-policing-profile
  /rests/operations/network-topology:network-topology/topology=topology-netconf/node=305250001/yang-ext:mount/policing-profile-1-0%3Amodify-policing-profile:
    parameters:
      - $ref: '#/components/parameters/mountName'
    post:
      operationId: postModifyPolicingProfile
      summary: 'Modifies an existing PolicingProfile'
      tags:
        - IndividualServices
      security:
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - input
              properties:
                input:
                  type: object
                  required:
                    - policing-profile-to-be-modified
                  properties:
                    policing-profile-to-be-modified:
                      type: string
                    external-label:
                      type: string
                    marker-mode:
                      type: string
                      enum:
                        - 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_BLIND'
                        - 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_AWARE'
                        - 'policing-profile-1-0:MARKER_MODE_TYPE_NOT_YET_DEFINED'
                    policer-kind:
                      type: string
                      enum:
                        - 'policing-profile-1-0:POLICER_KIND_TYPE_SINGLE_RATE_THREE_COLOR'
                        - 'policing-profile-1-0:POLICER_KIND_TYPE_TWO_RATE_THREE_COLOR'
                        - 'policing-profile-1-0:POLICER_KIND_TYPE_NOT_YET_DEFINED'
                    committed-information-rate:
                      type: string
                    committed-burst-size:
                      type: string
                    excess-burst-size:
                      type: string
                    peak-information-rate:
                      type: string
                    peak-burst-size:
                      type: string
              example:
                input:
                  policing-profile-to-be-modified = 'poliPro3'
                  externalLabel = 'modifiedLabel'
                  markerMode = 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_BLIND'
                  policerKind = 'policing-profile-1-0:POLICER_KIND_TYPE_SINGLE_RATE_THREE_COLOR'
                  committedInformationRate = '9999'
                  committedBurstSize = '128'
                  excessBurstSize = '256'
                  peakInformationRate = '99999'
                  peakBurstSize = '256'
      responses:
        '204':
          description: 'Instance of PolicingProfile updated'
  /rests/data/network-topology:network-topology/topology=topology-netconf/node=305250001/yang-ext:mount/core-model-1-4:control-construct/profile-collection/profile=poliPro3b/policing-profile-1-0:policing-profile-pac/policing-profile-configuration:
    parameters:
      - $ref: '#/components/parameters/mountName'
      - $ref: '#/components/parameters/uuid'
      - $ref: '#/components/parameters/fields'
    get:
      operationId: getPolicingProfileConfiguration
      summary: 'Provides PolicingProfileConfiguration from device'
      tags:
        - IndividualServices
      security:
        - basicAuth: []
      responses:
        '200':
          description: 'PolicingProfileConfiguration provided from device'
          content:
            application/json:
              schema:
                type: object
                required:
                  - policing-profile-1-0:policing-profile-configuration
                properties:
                  policing-profile-1-0:policing-profile-configuration:
                    $ref: '#/components/schemas/policing-profile-configuration'
                example:
                  policing-profile-1-0:policing-profile-configuration:
                    external-label: 'modifiedLabel'
                    marker-mode: 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_BLIND'
                    policer-kind: 'policing-profile-1-0:POLICER_KIND_TYPE_SINGLE_RATE_THREE_COLOR'
                    committed-information-rate: 9999
                    committed-burst-size: 128
                    excess-burst-size: -1
                    peak-information-rate: 99999
                    peak-burst-size: 256
  # /rests/operations/network-topology:network-topology/topology=topology-netconf/node=305250001/yang-ext:mount/policing-profile-1-0:delete-policing-profile
  /rests/operations/network-topology:network-topology/topology=topology-netconf/node=305250001/yang-ext:mount/policing-profile-1-0%3Adelete-policing-profile:
    parameters:
      - $ref: '#/components/parameters/mountName'
    post:
      operationId: postDeletePolicingProfile
      summary: 'Deletes an instance of PolicingProfile'
      tags:
        - IndividualServices
      security:
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - input
              properties:
                input:
                  type: object
                  required:
                  - obsolete-policing-profile
                  properties:
                    obsolete-policing-profile:
                      type: string
              example:
                input:
                  obsolete-policing-profile = 'poliPro3'
      responses:
        '204':
          description: 'Instance of PolicingProfile deleted'


########################################################################################################################
#   Generic Paths
########################################################################################################################
  /generic/core-model-1-4:network-control-domain=cache/control-construct={mountName}/profile-collection/profile={uuid}/policing-profile-1-0:policing-profile-pac/policing-profile-capability:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
      - $ref: '#/components/parameters/uuid'
      - $ref: '#/components/parameters/fields'
    get:
      operationId: getCachedPolicingProfileCapability
      summary: 'Provides PolicingProfileCapability from cache'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      responses:
        '200':
          description: 'PolicingProfileCapability provided from cache'
          content:
            application/json:
              schema:
                type: object
                required:
                  - policing-profile-1-0:policing-profile-capability
                properties:
                  policing-profile-1-0:policing-profile-capability:
                    $ref: '#/components/schemas/policing-profile-capability'
                example:
                  policing-profile-1-0:policing-profile-capability:
                    profile-naming-is-avail: true
                    supported-marker-mode-list:
                      - 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_BLIND'
                      - 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_AWARE'
                    supported-policer-kind-list:
                      - 'policing-profile-1-0:POLICER_KIND_TYPE_SINGLE_RATE_THREE_COLOR'
                      - 'policing-profile-1-0:POLICER_KIND_TYPE_TWO_RATE_THREE_COLOR'
                    information-rate-min: 0
                    information-rate-max: 0
                    burst-size-min: 0
                    burst-size-max: 0
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'
  /generic/core-model-1-4:network-control-domain=cache/control-construct={mountName}/profile-collection/profile={uuid}/policing-profile-1-0:policing-profile-pac/policing-profile-configuration:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
      - $ref: '#/components/parameters/uuid'
      - $ref: '#/components/parameters/fields'
    get:
      operationId: getCachedPolicingProfileConfiguration
      summary: 'Provides PolicingProfileConfiguration from cache'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      responses:
        '200':
          description: 'PolicingProfileConfiguration provided from cache'
          content:
            application/json:
              schema:
                type: object
                required:
                  - policing-profile-1-0:policing-profile-configuration
                properties:
                  policing-profile-1-0:policing-profile-configuration:
                    $ref: '#/components/schemas/policing-profile-configuration'
                example:
                  policing-profile-1-0:policing-profile-configuration:
                    external-label: 'string'
                    marker-mode: 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_BLIND'
                    policer-kind: 'policing-profile-1-0:POLICER_KIND_TYPE_SINGLE_RATE_THREE_COLOR'
                    committed-information-rate: 0
                    committed-burst-size: 0
                    excess-burst-size: 0
                    peak-information-rate: 0
                    peak-burst-size: 0
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'

  /generic/core-model-1-4:network-control-domain=live/control-construct={mountName}/policing-profile-1-0:create-policing-profile:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
    post:
      operationId: postCreatePolicingProfile
      summary: 'Creates new instance of PolicingProfile'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - input
              properties:
                input:
                  type: object
                  required:
                    - marker-mode
                    - policer-kind
                    - committed-information-rate
                    - committed-burst-size
                  properties:
                    external-label:
                      type: string
                    marker-mode:
                      type: string
                      enum:
                        - 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_BLIND'
                        - 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_AWARE'
                        - 'policing-profile-1-0:MARKER_MODE_TYPE_NOT_YET_DEFINED'
                    policer-kind:
                      type: string
                      enum:
                        - 'policing-profile-1-0:POLICER_KIND_TYPE_SINGLE_RATE_THREE_COLOR'
                        - 'policing-profile-1-0:POLICER_KIND_TYPE_TWO_RATE_THREE_COLOR'
                        - 'policing-profile-1-0:POLICER_KIND_TYPE_NOT_YET_DEFINED'
                    committed-information-rate:
                      type: string
                    committed-burst-size:
                      type: string
                    excess-burst-size:
                      type: string
                    peak-information-rate:
                      type: string
                    peak-burst-size:
                      type: string
      responses:
        '200':
          description: 'New instance of PolicingProfile created'
          content:
            application/json:
              schema:
                type: object
                required:
                  - policing-profile-1-0:output
                properties:
                  policing-profile-1-0:output:
                    type: object
                    required:
                      - created-policing-profile
                    properties:
                      created-policing-profile:
                        type: string
                example:
                  policing-profile-1-0:output:
                    created-policing-profile: 'string'
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'
  /generic/core-model-1-4:network-control-domain=live/control-construct={mountName}/policing-profile-1-0:modify-policing-profile:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
    post:
      operationId: postModifyPolicingProfile
      summary: 'Modifies an existing PolicingProfile'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - input
              properties:
                input:
                  type: object
                  required:
                    - policing-profile-to-be-modified
                  properties:
                    policing-profile-to-be-modified:
                      type: string
                    external-label:
                      type: string
                    marker-mode:
                      type: string
                      enum:
                        - 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_BLIND'
                        - 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_AWARE'
                        - 'policing-profile-1-0:MARKER_MODE_TYPE_NOT_YET_DEFINED'
                    policer-kind:
                      type: string
                      enum:
                        - 'policing-profile-1-0:POLICER_KIND_TYPE_SINGLE_RATE_THREE_COLOR'
                        - 'policing-profile-1-0:POLICER_KIND_TYPE_TWO_RATE_THREE_COLOR'
                        - 'policing-profile-1-0:POLICER_KIND_TYPE_NOT_YET_DEFINED'
                    committed-information-rate:
                      type: string
                    committed-burst-size:
                      type: string
                    excess-burst-size:
                      type: string
                    peak-information-rate:
                      type: string
                    peak-burst-size:
                      type: string
      responses:
        '204':
          description: 'Instance of PolicingProfile updated'
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'
  /generic/core-model-1-4:network-control-domain=live/control-construct={mountName}/policing-profile-1-0:delete-policing-profile:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
    post:
      operationId: postDeletePolicingProfile
      summary: 'Deletes an instance of PolicingProfile'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - input
              properties:
                input:
                  type: object
                  required:
                  - obsolete-policing-profile
                  properties:
                    obsolete-policing-profile:
                      type: string
      responses:
        '204':
          description: 'Instance of PolicingProfile deleted'
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'


########################################################################################################################
#   Common Components
########################################################################################################################
components:
  parameters:
    user:
      name: user
      in: header
      required: true
      schema:
        type: string
        example: 'User Name'
      description: 'User identifier from the system starting the service call'
    originator:
      name: originator
      in: header
      required: true
      schema:
        type: string
        minLength: 3
        example: 'Resolver'
      description: >
        'Identification for the system consuming the API, as defined in
         [/core-model-1-4:control-construct/logical-termination-point={uuid}/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/application-name]'
    x-correlator:
      name: x-correlator
      in: header
      required: true
      schema:
        type: string
        pattern: '^[0-9A-Fa-f]{8}(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}$'
        description: 'Empty string accepted from external applications.'
        example: '550e8400-e29b-11d4-a716-446655440000'
      description: 'UUID for the service execution flow that allows to correlate requests and responses'
    trace-indicator:
      name: trace-indicator
      in: header
      required: true
      schema:
        type: string
        pattern: '^([0-9]+)(\.([0-9]+))*$'
        description: 'Empty string accepted from external applications.'
        example: '1.3.1'
      description: 'Sequence of request numbers along the flow'
    customer-journey:
      name: customer-journey
      in: header
      required: true
      schema:
        type: string
        example: 'Unknown value'
      description: 'Holds information supporting customer’s journey to which the execution applies'
    mountName:
      name: mountName
      in: path
      required: true
      schema:
        type: string
        example: '222250001'
      description: 'The mountName of the device that is addressed by the request'
    uuid:
      name: uuid
      in: path
      required: true
      schema:
        type: string
        example: 'LTP-MWPS-TTP-1-1'
      description: 'Instance identifier that is unique within the device'
    uuid1:
      name: uuid1
      in: path
      required: true
      schema:
        type: string
        example: 'LTP-MWPS-TTP-1-1'
      description: 'Another instance identifier that is unique within the device'
    localId:
      name: localId
      in: path
      required: true
      schema:
        type: string
        example: 'LP-MWPS-TTP-1-1'
      description: 'Instance identifier that is unique within its list'
    fields:
      name: fields
      in: query
      required: false
      schema:
        type: string
        example: 'node(node-id;netconf-node-topology:connection-status)'
      description: 'Query parameter to filter ressources according to RFC8040 fields filter spec'
  responses:
    responseForErroredServiceRequests:
      description: 'Response in case of errored service requests'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorDescription'
      headers:
        x-correlator:
          schema:
            type: string
            pattern: '^[0-9A-Fa-f]{8}(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}$'
            example: '550e8400-e29b-11d4-a716-446655440000'
          description: 'UUID for the service execution flow that allows to correlate requests and responses. Its value must be identical at the response compared with its corresponding request'
        exec-time:
          schema:
            type: integer
            example: 1100
          description: 'Value written by the service provider, reporting the total elapsed time for the execution, including all the additional processing needed to retrieve the data from the backend service. Expressed in milliseconds'
        backend-time:
          schema:
            type: integer
            example: 850
          description: 'Value written by the service provider, reporting the elapsed time for data retrieval from the backend (service invocation, database access…). Expressed in milliseconds'
    responseForErroredOamRequests:
      description: 'Response in case of errored OaM requests'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorDescription'
  headers:
    x-correlator:
      schema:
        type: string
        example: '550e8400-e29b-11d4-a716-446655440000'
      description: 'UUID for the service execution flow that allows to correlate requests and responses. Its value must be identical at the response compared with its corresponding request'
    exec-time:
      schema:
        type: integer
        example: 1100
      description: 'Value written by the service provider, reporting the total elapsed time for the execution, including all the additional processing needed to retrieve the data from the backend service. Expressed in milliseconds'
    backend-time:
      schema:
        type: integer
        example: 850
      description: 'Value written by the service provider, reporting the elapsed time for data retrieval from the backend (service invocation, database access…). Expressed in milliseconds'
    life-cycle-state:
      schema:
        type: string
        enum:
          - 'EXPERIMENTAL'
          - 'OPERATIONAL'
          - 'DEPRECATED'
          - 'OBSOLETE'
          - 'UNKNOWN'
          - 'NOT_YET_DEFINED'
        example: 'EXPERIMENTAL'
  schemas:
    errorDescription:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    policing-profile-capability:
      type: object
      required:
        - profile-naming-is-avail
        - information-rate-min
        - information-rate-max
        - burst-size-min
        - burst-size-max
      properties:
        profile-naming-is-avail:
          type: boolean
        supported-marker-mode-list:
          type: array
          minItems: 0
          items:
            type: string
            enum:
              - 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_BLIND'
              - 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_AWARE'
              - 'policing-profile-1-0:MARKER_MODE_TYPE_NOT_YET_DEFINED'
        supported-policer-kind-list:
          type: array
          minItems: 0
          items:
            type: string
            enum:
              - 'policing-profile-1-0:POLICER_KIND_TYPE_SINGLE_RATE_THREE_COLOR'
              - 'policing-profile-1-0:POLICER_KIND_TYPE_TWO_RATE_THREE_COLOR'
              - 'policing-profile-1-0:POLICER_KIND_TYPE_NOT_YET_DEFINED'
        information-rate-min:
          type: integer
          format: int32
        information-rate-max:
          type: integer
          format: int32
        burst-size-min:
          type: integer
          format: int16
        burst-size-max:
          type: integer
          format: int16
    policing-profile-configuration:
      type: object
      required:
        - external-label
        - marker-mode
        - policer-kind
        - committed-information-rate
        - committed-burst-size
        - excess-burst-size
        - peak-information-rate
        - peak-burst-size
      properties:
        external-label:
          type: string
        marker-mode:
          type: string
          enum:
            - 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_BLIND'
            - 'policing-profile-1-0:MARKER_MODE_TYPE_COLOR_AWARE'
            - 'policing-profile-1-0:MARKER_MODE_TYPE_NOT_YET_DEFINED'
        policer-kind:
          type: string
          enum:
            - 'policing-profile-1-0:POLICER_KIND_TYPE_SINGLE_RATE_THREE_COLOR'
            - 'policing-profile-1-0:POLICER_KIND_TYPE_TWO_RATE_THREE_COLOR'
            - 'policing-profile-1-0:POLICER_KIND_TYPE_NOT_YET_DEFINED'
        committed-information-rate:
          type: integer
          format: int32
        committed-burst-size:
          type: integer
          format: int32
        excess-burst-size:
          type: integer
          format: int32
        peak-information-rate:
          type: integer
          format: int32
        peak-burst-size:
          type: integer
          format: int32

  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: operation-key
    basicAuth:
      type: http
      scheme: basic
